### ISSUE TITLE
Bad logical operators position

### ISSUE THREAD

**Issue by mirh** [LongSoft/Universal-IFR-Extractor#25] opened 2022-04-14 01:29 UTC
So, take for example this structure from my laptop [bios](https://www.acer.com/ac/en/US/content/support-product/8305) (FE3542FE-C1D3-4EF8-657C-8048606FF670)
```
Form: Boot, FormId: 0x1 {01 86 01 00 CA 00}
	Subtitle: Statement.Prompt:  , Flags: 0x0 {02 87 54 01 00 00 00}
	End {29 02}
	Gray Out If {19 82}
		True {46 02}
		Suppress If {0A 82}
			QuestionId: 0x6 equals value in list (0x1) {14 08 06 00 01 00 01 00}
			Gray Out If {19 82}
				QuestionId: 0x6 equals value 0x2 {12 86 06 00 02 00}
					QuestionId: 0x1 equals value in list (0x2, 0x3) {14 0A 01 00 02 00 02 00 03 00}
					QuestionId: 0x2 equals value 0x1 {12 06 02 00 01 00}
					And {15 02}
					Or {16 02}
				End {29 02}
				One Of: Boot Mode:, VarStoreInfo (VarOffset/VarName): 0x79, VarStore: 0x1234, QuestionId: 0xA015, Size: 1, Min: 0x1, Max 0x2, Step: 0x0 {05 91 CB 00 CC 00 15 A0 34 12 79 00 04 10 01 02 00}
					One Of Option: UEFI, Value (8 bit): 0x2 (default) {09 07 CD 00 10 00 02}
					Suppress If {0A 82}
						True {46 02}
						One Of Option: Legacy, Value (8 bit): 0x1 {09 07 CE 00 00 00 01}
					End If {29 02}
				End One Of {29 02}
			End If {29 02}
		End If {29 02}
	End If {29 02}
```
Even though, I would guess, the *And* and *Or* should somehow mix with the surrounding/preceding statements.. they are instead  at the end of the relative block. 
It becomes then next to impossible to understand the QuestionIds meaning.

**Comment by NikolajSchlej** [comment] 2022-11-08 09:06
Closing as unable to reproduce using IFRExtractor-RS v1.4.0, please migrate to it.
Open an issue in that repo if you believe the problem is reproducible there.

**Closed as completed by NikolajSchlej** 2022-11-08 09:06 UTC
